apiVersion: v1
kind: Service
metadata:
  annotations:
    service.alpha.openshift.io/serving-cert-secret-name: windows-machine-config-operator-tls
  creationTimestamp: null
  labels:
    name: windows-exporter
  name: windows-exporter
spec:
  ports:
  - name: metrics
    port: 9182
    protocol: TCP
    targetPort: 9182
status:
  loadBalancer: {}
