kind: Service
apiVersion: v1
metadata:
  name: windows-exporter
  labels:
    name: windows-exporter
  annotations:
    service.alpha.openshift.io/serving-cert-secret-name: windows-machine-config-operator-tls
spec:
  ports:
    - name: metrics
      protocol: TCP
      port: 9182
      targetPort: 9182
