apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: example-windows-pvc
  namespace: windows-storage-example
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 2Gi
  storageClassName: example-windows-sc
  volumeMode: Filesystem
